# coding: utf-8

"""
    Klaviyo API

    The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.  # noqa: E501

    The version of the OpenAPI document: 2023-08-15
    Contact: developers@klaviyo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr
from openapi_client.models.subscription_create_job_create_query_resource_object_attributes_profiles import SubscriptionCreateJobCreateQueryResourceObjectAttributesProfiles

class SubscriptionCreateJobCreateQueryResourceObjectAttributes(BaseModel):
    """
    SubscriptionCreateJobCreateQueryResourceObjectAttributes
    """
    custom_source: Optional[StrictStr] = Field(None, description="A custom method detail or source to store on the consent records.")
    profiles: SubscriptionCreateJobCreateQueryResourceObjectAttributesProfiles = Field(...)
    __properties = ["custom_source", "profiles"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> SubscriptionCreateJobCreateQueryResourceObjectAttributes:
        """Create an instance of SubscriptionCreateJobCreateQueryResourceObjectAttributes from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of profiles
        if self.profiles:
            _dict['profiles'] = self.profiles.to_dict()
        # set to None if custom_source (nullable) is None
        # and __fields_set__ contains the field
        if self.custom_source is None and "custom_source" in self.__fields_set__:
            _dict['custom_source'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> SubscriptionCreateJobCreateQueryResourceObjectAttributes:
        """Create an instance of SubscriptionCreateJobCreateQueryResourceObjectAttributes from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return SubscriptionCreateJobCreateQueryResourceObjectAttributes.parse_obj(obj)

        _obj = SubscriptionCreateJobCreateQueryResourceObjectAttributes.parse_obj({
            "custom_source": obj.get("custom_source"),
            "profiles": SubscriptionCreateJobCreateQueryResourceObjectAttributesProfiles.from_dict(obj.get("profiles")) if obj.get("profiles") is not None else None
        })
        return _obj

