# coding: utf-8

"""
    Klaviyo API

    The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.  # noqa: E501

    The version of the OpenAPI document: 2023-08-15
    Contact: developers@klaviyo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictStr
from openapi_client.models.tag_group_enum import TagGroupEnum

class TagCreateQueryResourceObjectRelationshipsTagGroupData(BaseModel):
    """
    TagCreateQueryResourceObjectRelationshipsTagGroupData
    """
    type: TagGroupEnum = Field(...)
    id: StrictStr = Field(...)
    __properties = ["type", "id"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TagCreateQueryResourceObjectRelationshipsTagGroupData:
        """Create an instance of TagCreateQueryResourceObjectRelationshipsTagGroupData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TagCreateQueryResourceObjectRelationshipsTagGroupData:
        """Create an instance of TagCreateQueryResourceObjectRelationshipsTagGroupData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TagCreateQueryResourceObjectRelationshipsTagGroupData.parse_obj(obj)

        _obj = TagCreateQueryResourceObjectRelationshipsTagGroupData.parse_obj({
            "type": obj.get("type"),
            "id": obj.get("id")
        })
        return _obj

