# coding: utf-8

"""
    Klaviyo API

    The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

    The version of the OpenAPI document: 2024-02-15
    Contact: developers@klaviyo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class CampaignValuesReportEnum(str, Enum):
    """
    CampaignValuesReportEnum
    """

    """
    allowed enum values
    """
    CAMPAIGN_MINUS_VALUES_MINUS_REPORT = 'campaign-values-report'

    @classmethod
    def from_json(cls, json_str: str) -> CampaignValuesReportEnum:
        """Create an instance of CampaignValuesReportEnum from a JSON string"""
        return CampaignValuesReportEnum(json.loads(json_str))


