# coding: utf-8

"""
    Klaviyo API

    The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

    Contact: developers@klaviyo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CatalogCategoryBulkCreateJobEnum(str, Enum):
    """
    CatalogCategoryBulkCreateJobEnum
    """

    """
    allowed enum values
    """
    CATALOG_MINUS_CATEGORY_MINUS_BULK_MINUS_CREATE_MINUS_JOB = 'catalog-category-bulk-create-job'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CatalogCategoryBulkCreateJobEnum from a JSON string"""
        return cls(json.loads(json_str))


