# coding: utf-8

"""
    Klaviyo API

    The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

    The version of the OpenAPI document: 2025-04-15
    Contact: developers@klaviyo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.get_campaign_message_response_compound_document_data_all_of_relationships_campaign import GetCampaignMessageResponseCompoundDocumentDataAllOfRelationshipsCampaign
from openapi_client.models.get_campaign_message_response_compound_document_data_all_of_relationships_image import GetCampaignMessageResponseCompoundDocumentDataAllOfRelationshipsImage
from openapi_client.models.get_campaign_message_response_compound_document_data_all_of_relationships_template import GetCampaignMessageResponseCompoundDocumentDataAllOfRelationshipsTemplate
from typing import Optional, Set
from typing_extensions import Self

class GetCampaignMessageResponseCompoundDocumentDataAllOfRelationships(BaseModel):
    """
    GetCampaignMessageResponseCompoundDocumentDataAllOfRelationships
    """ # noqa: E501
    campaign: Optional[GetCampaignMessageResponseCompoundDocumentDataAllOfRelationshipsCampaign] = None
    template: Optional[GetCampaignMessageResponseCompoundDocumentDataAllOfRelationshipsTemplate] = None
    image: Optional[GetCampaignMessageResponseCompoundDocumentDataAllOfRelationshipsImage] = None
    __properties: ClassVar[List[str]] = ["campaign", "template", "image"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetCampaignMessageResponseCompoundDocumentDataAllOfRelationships from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of campaign
        if self.campaign:
            _dict['campaign'] = self.campaign.to_dict()
        # override the default output from pydantic by calling `to_dict()` of template
        if self.template:
            _dict['template'] = self.template.to_dict()
        # override the default output from pydantic by calling `to_dict()` of image
        if self.image:
            _dict['image'] = self.image.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetCampaignMessageResponseCompoundDocumentDataAllOfRelationships from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "campaign": GetCampaignMessageResponseCompoundDocumentDataAllOfRelationshipsCampaign.from_dict(obj["campaign"]) if obj.get("campaign") is not None else None,
            "template": GetCampaignMessageResponseCompoundDocumentDataAllOfRelationshipsTemplate.from_dict(obj["template"]) if obj.get("template") is not None else None,
            "image": GetCampaignMessageResponseCompoundDocumentDataAllOfRelationshipsImage.from_dict(obj["image"]) if obj.get("image") is not None else None
        })
        return _obj


