# coding: utf-8

"""
    Klaviyo API

    The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

    Contact: developers@klaviyo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class MappedMetricEnum(str, Enum):
    """
    MappedMetricEnum
    """

    """
    allowed enum values
    """
    MAPPED_MINUS_METRIC = 'mapped-metric'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MappedMetricEnum from a JSON string"""
        return cls(json.loads(json_str))


