# coding: utf-8

"""
    Klaviyo API

    The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

    Contact: developers@klaviyo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.api_schema_property import APISchemaProperty
from openapi_client.models.embedded_object_schema_resource_object_attributes_source_mapping import EmbeddedObjectSchemaResourceObjectAttributesSourceMapping
from typing import Optional, Set
from typing_extensions import Self

class ObjectSchemaCreateQueryResourceObjectAttributes(BaseModel):
    """
    ObjectSchemaCreateQueryResourceObjectAttributes
    """ # noqa: E501
    title: StrictStr = Field(description="The title for this object schema")
    properties: List[APISchemaProperty] = Field(description="Properties of the object schema")
    description: Optional[StrictStr] = Field(default=None, description="The description of this object schema")
    status: Optional[StrictStr] = Field(default='draft', description="The status to create this object schema in. Defaults to `draft`. Setting `active` activates the schema immediately; while activation is in progress, reads may report a `publishing` status.")
    required: Optional[List[StrictStr]] = Field(default=None, description="Properties that are required on the object schema")
    source_mapping: Optional[EmbeddedObjectSchemaResourceObjectAttributesSourceMapping] = Field(default=None, alias="source-mapping")
    __properties: ClassVar[List[str]] = ["title", "properties", "description", "status", "required", "source-mapping"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['active', 'draft']):
            raise ValueError("must be one of enum values ('active', 'draft')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ObjectSchemaCreateQueryResourceObjectAttributes from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in properties (list)
        _items = []
        if self.properties:
            for _item in self.properties:
                if _item:
                    _items.append(_item.to_dict())
            _dict['properties'] = _items
        # override the default output from pydantic by calling `to_dict()` of source_mapping
        if self.source_mapping:
            _dict['source-mapping'] = self.source_mapping.to_dict()
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if status (nullable) is None
        # and model_fields_set contains the field
        if self.status is None and "status" in self.model_fields_set:
            _dict['status'] = None

        # set to None if required (nullable) is None
        # and model_fields_set contains the field
        if self.required is None and "required" in self.model_fields_set:
            _dict['required'] = None

        # set to None if source_mapping (nullable) is None
        # and model_fields_set contains the field
        if self.source_mapping is None and "source_mapping" in self.model_fields_set:
            _dict['source-mapping'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ObjectSchemaCreateQueryResourceObjectAttributes from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "title": obj.get("title"),
            "properties": [APISchemaProperty.from_dict(_item) for _item in obj["properties"]] if obj.get("properties") is not None else None,
            "description": obj.get("description"),
            "status": obj.get("status") if obj.get("status") is not None else 'draft',
            "required": obj.get("required"),
            "source-mapping": EmbeddedObjectSchemaResourceObjectAttributesSourceMapping.from_dict(obj["source-mapping"]) if obj.get("source-mapping") is not None else None
        })
        return _obj


