# coding: utf-8

"""
    Klaviyo API

    The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.  # noqa: E501

    The version of the OpenAPI document: 2023-09-15
    Contact: developers@klaviyo.com
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.api_lists_.post import CreateList
from openapi_client.paths.api_lists_id_relationships_profiles_.post import CreateListRelationships
from openapi_client.paths.api_lists_id_.delete import DeleteList
from openapi_client.paths.api_lists_id_relationships_profiles_.delete import DeleteListRelationships
from openapi_client.paths.api_lists_id_.get import GetList
from openapi_client.paths.api_lists_id_profiles_.get import GetListProfiles
from openapi_client.paths.api_lists_id_relationships_profiles_.get import GetListRelationshipsProfiles
from openapi_client.paths.api_lists_id_relationships_tags_.get import GetListRelationshipsTags
from openapi_client.paths.api_lists_id_tags_.get import GetListTags
from openapi_client.paths.api_lists_.get import GetLists
from openapi_client.paths.api_lists_id_.patch import UpdateList


class ListsApi(
    CreateList,
    CreateListRelationships,
    DeleteList,
    DeleteListRelationships,
    GetList,
    GetListProfiles,
    GetListRelationshipsProfiles,
    GetListRelationshipsTags,
    GetListTags,
    GetLists,
    UpdateList,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
