# coding: utf-8

"""
    Klaviyo API

    The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.  # noqa: E501

    The version of the OpenAPI document: 2023-09-15
    Contact: developers@klaviyo.com
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.api_profiles_.post import CreateProfile
from openapi_client.paths.api_push_tokens_.post import CreatePushToken
from openapi_client.paths.api_profiles_id_.get import GetProfile
from openapi_client.paths.api_profiles_id_lists_.get import GetProfileLists
from openapi_client.paths.api_profiles_id_relationships_lists_.get import GetProfileRelationshipsLists
from openapi_client.paths.api_profiles_id_relationships_segments_.get import GetProfileRelationshipsSegments
from openapi_client.paths.api_profiles_id_segments_.get import GetProfileSegments
from openapi_client.paths.api_profiles_.get import GetProfiles
from openapi_client.paths.api_profile_merge_.post import MergeProfiles
from openapi_client.paths.api_profile_subscription_bulk_create_jobs_.post import SubscribeProfiles
from openapi_client.paths.api_profile_suppression_bulk_create_jobs_.post import SuppressProfiles
from openapi_client.paths.api_profile_subscription_bulk_delete_jobs_.post import UnsubscribeProfiles
from openapi_client.paths.api_profile_suppression_bulk_delete_jobs_.post import UnsuppressProfiles
from openapi_client.paths.api_profiles_id_.patch import UpdateProfile


class ProfilesApi(
    CreateProfile,
    CreatePushToken,
    GetProfile,
    GetProfileLists,
    GetProfileRelationshipsLists,
    GetProfileRelationshipsSegments,
    GetProfileSegments,
    GetProfiles,
    MergeProfiles,
    SubscribeProfiles,
    SuppressProfiles,
    UnsubscribeProfiles,
    UnsuppressProfiles,
    UpdateProfile,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
